### ISSUE TITLE
Heap Space

### ISSUE THREAD

**Issue by ansjob** [ansjob/optimalt-yatzy#1]
Jag får slut på heapspace när min dator försöker allokera minne för att spara alla actions. Hur mycket brukar du köra?

Raden där felet inträffar:
```actions = new byte[3][Hand.MAX_INDEX + 1][ScoreCard.MAX_INDEX + 1];

```

Btw, ser jävligt bra ut med roll 0-2 ! :)
```

**Comment by marcular** [comment]
Oj fan. :P

Har kvar en gammal inställning med heap space på 6GB

**Comment by ansjob** [comment]
Weak att jag bara har 4 GB då =/

**Comment by ansjob** [comment]
Nu lagrar vi det på fil istället (som tydligen bara blev 1.5GB)
