### ISSUE TITLE
upperTotal

### ISSUE THREAD

**Issue by ansjob** [ansjob/optimalt-yatzy#2]
Stämmer detta verkligen?

```
if (score + upperTotal >= 63)
        score += 50;
return score;
```

Jag tänker mig i scenariot där man redan har t ex 67 poäng i upperTotal och kryssar i en etta. Det får man ju bara en poäng för och inte 51. 

Förslag på ändring:

```
if (upperTotal < 63 && score + upperTotal >= 63)
        score += 50:
return score
```

**Comment by marcular** [comment]
Det har du jäkligt rätt i :P
Ändringen ser otroligt mycket bättre ut.
